CNB\ server=CNB server
Repository\ path=Repository path
Events=Events
Ref\ filter=Ref filter
Pull\ request\ source\ branch\ filter=Pull request source branch filter
Pull\ request\ target\ branch\ filter=Pull request target branch filter
Include\ draft\ pull\ requests=Include draft pull requests
Skip\ commits\ with\ CI\ skip\ markers=Skip commits with CI skip markers
Build\ pull\ requests\ only\ for\ a\ new\ source\ revision=Build pull requests only for a new source revision
Required\ pull\ request\ labels=Required pull request labels
Excluded\ pull\ request\ labels=Excluded pull request labels
Pull\ request\ comment\ pattern\ (RE2/J)=Pull request comment pattern (RE2/J)
Minimum\ comment\ author\ role=Minimum comment author role
Cancel\ superseded\ pending\ builds=Cancel superseded pending builds
Cancel\ superseded\ running\ pull\ request\ builds=Cancel superseded running pull request builds
