Include\ draft/WIP\ pull\ requests=Include draft/WIP pull requests
Source\ branch\ glob=Source branch glob
Target\ branch\ glob=Target branch glob
Required\ labels=Required labels
Excluded\ labels=Excluded labels
